### ISSUE TITLE
意図しないnoticeが表示される

### ISSUE THREAD

**Issue by saddyYuji** [hoshizakana/gooCD#84]
ユーザログイン中
↓
ログアウト
↓
トップページ（リダイレクト）
↓
ログイン画面　…ここで「ログアウトしました」の表示がされる

noticeの有効期限がどうなっているのか調べ、意図しないnoticeの表示をさせないようにする

**Comment by NaofumiOkamoto** [comment]
表示のタイミングは修正しました。
レイアウト修正がまだなのと、
新規登録時の日本語化が忘れてました。

**Comment by NaofumiOkamoto** [comment]
新規登録ができない状況も含め、修正
