### ISSUE TITLE
日付検索した後、フォームに入る値が気持ち悪い

### ISSUE THREAD

**Issue by saddyYuji** [hoshizakana/gooCD#92]
created_atはDateTime型だが、これをDate型に変えることで表示はキモくならない
たぶんできる→http://murajun1978.hatenadiary.com/entry/2014/11/04/004659

やるの後回しですみません

**Comment by NaofumiOkamoto** [comment]
config/initiaraize/にransack.rb作成し、
Ransack.configure do |config|
 config.add_predicate 'lteq_end_of_day',
                         :arel_predicate => 'lteq',
                         :formatter => proc { |v| v.end_of_day },
                        :compounds => false
end
を記載して、f.date_field :created_at_lteq_end_of_dayにして実装完了
